// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ///Enter key,
    appId: ///Enter ID,
    messagingSenderId: '721921639359',
    projectId: 'ms-test-6358d',
    authDomain: 'ms-test-6358d.firebaseapp.com',
    databaseURL: 'https://ms-test-6358d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ms-test-6358d.firebasestorage.app',
    measurementId: 'G-696G2FSLTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ///Enter key,
    appId: ///Enter ID,
    messagingSenderId: '721921639359',
    projectId: 'ms-test-6358d',
    databaseURL: 'https://ms-test-6358d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ms-test-6358d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ///Enter key,
    appId: ///Enter ID,
    messagingSenderId: '721921639359',
    projectId: 'ms-test-6358d',
    databaseURL: 'https://ms-test-6358d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ms-test-6358d.firebasestorage.app',
    iosBundleId: 'com.example.moveSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ///Enter key,
    appId: ///Enter ID,
    messagingSenderId: '721921639359',
    projectId: 'ms-test-6358d',
    databaseURL: 'https://ms-test-6358d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ms-test-6358d.firebasestorage.app',
    iosBundleId: 'com.example.moveSafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: ///Enter key,
    appId: ///Enter ID,
    messagingSenderId: '721921639359',
    projectId: 'ms-test-6358d',
    authDomain: 'ms-test-6358d.firebaseapp.com',
    databaseURL: 'https://ms-test-6358d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ms-test-6358d.firebasestorage.app',
    measurementId: 'G-0TMHX4NYSE',
  );

}
